### ISSUE TITLE
where can i find a merged data for all 20 types tissue 

### ISSUE THREAD

**Issue by YidingZhang117** [czbiohub/tabula-muris#220]
hello,
       I can find separate .Robj files for each tissue in figshare, but I wonder how to get an integrated and processed data for all tissues(in one single Robj file)? I find FACS_all.Robj mentioned in your code, could you please tell me where to find this file? Because I want to compare data from different tissue, so I don't know where to get a complete and batch normalized data? Thank you!

**Comment by aopisco** [comment]
hi @ZenobiaDing117, thanks for your interest. Is the data here helpful?

https://github.com/czbiohub/tabula-muris-vignettes/tree/master/data

**Comment by guy531** [comment]
Hi,
I have the same issue. Couldn't find the FACS_all.Robj file. In the link you provided this doesn't exist as well.

I have very little experience with the Seurate program so I might be missing something. Are any of the files in the link you provided can be converted into this FACS_all.Robj file? 
Also from what I understand the size of this file should be at least 14 GB (Which is the combined size of the .Robj for all the other tissues). I could not find any files with a similar size on both projects.

Any help on the subject would be greatly appreciated.

**Comment by aopisco** [comment]
Hi @guy531, did you download the .Rds file in the link and follow the steps below that?

**Comment by guy531** [comment]
Thank you for the quick response.

I downloaded the .Rds file in the link that you provided, and followed the steps below it. I also downloaded the 'vigenettes' scripts and run through all of them. 

However I could not find an example of how to create the fig. 2 results as in the main text. I only found examples that are related to individual tissues. Like the poster above me, I'm interested in comparing different tissues as is shown in file figure2a.R (using the  FACS_all.Robj file) in this repository, and not cells from the same tissue.

I would also like to point out that most of the scripts in their current condition can not be run with the latest version of Seurat, and even with a downgraded version of Seurat there are some errors/warnings that I suspect are caused by other dependencies that are also version based. It would be very helpful if you could provide a list of R dependencies and their versions that are required to run these programs.

As I said before, I have little experience with analyzing sc-RNA data using Seurate and I find your data/explanation extremely helpful in this regard, which clearly was a major part in your work's intention. Its just a shame that most of the scripts posted here at the present time can not run as is, especially for an inexperienced individual as myself. A complete **working** example of how the main figures were created is valuable.

**Comment by guy531** [comment]
Hello again, 

I figured it out eventually. For future users here is what you need to do:
- Install `Seurat 2.3.4` from the following link: https://cran.r-project.org/src/contrib/Archive/Seurat/

- For FACS analysis download `TM_facs_mat.rds` and `TM_facs_metadata.csv` from here: https://github.com/czbiohub/tabula-muris-vignettes/tree/master/data

- To create/analyse an .Robj file that contains all the tissues (for comparing tissues) follow the instructions presented in the file `ALL_FACS_Notebook.Rmd` here: https://github.com/czbiohub/tabula-muris/tree/master/00_data_ingest

- The end result of which is a file similar to `FACS_all.Robj`.

Note that in my case I needed at least 32GB RAM to analyze all the data from all tissues.

Thank you again for your support.

**Comment by aopisco** [comment]
@guy531 thanks for this. Would you like to add this information to the readme by doing a pull request? This is super useful for future users!
